'use client'

import { useMemo, type ComponentProps } from 'react'
import PanelCard from '../PanelCard'
import type { StoryboardPanelListItemProps } from '../StoryboardPanelList.types'

export function useStoryboardPanelListItemCardProps({
  storyboardId,
  panelCardLabels,
  videoRatio,
  item,
  onPanelUpdate,
  onPanelDelete,
  onOpenCharacterPicker,
  onOpenLocationPicker,
  onRemoveCharacter,
  onRemoveLocation,
  onRetryPanelSave,
  onRegeneratePanelImage,
  onOpenEditModal,
  onOpenAIDataModal,
  onSelectPanelCandidateIndex,
  onConfirmPanelCandidate,
  onCancelPanelCandidate,
  onClearPanelTaskError,
  onPreviewImage,
  onInsertAfter,
  onVariant,
  isInsertDisabled,
}: Omit<StoryboardPanelListItemProps, 'totalPanels'>) {
  const {
    panel,
    index,
    imageUrl,
    globalPanelNumber,
    isPanelModifying,
    isPanelDeleting,
    isPanelSaving,
    hasUnsavedChanges,
    panelSaveError,
    panelTaskRunning,
    panelFailedError,
    panelData,
    panelCandidateData,
  } = item

  return useMemo(
    () =>
      ({
        panel,
        panelData,
        labels: panelCardLabels,
        imageUrl,
        globalPanelNumber,
        storyboardId,
        videoRatio,
        isSaving: isPanelSaving,
        hasUnsavedChanges,
        saveErrorMessage: panelSaveError,
        isDeleting: isPanelDeleting,
        isModifying: isPanelModifying,
        isSubmittingPanelImageTask: panelTaskRunning,
        failedError: panelFailedError,
        candidateData: panelCandidateData,
        onUpdate: (updates) => onPanelUpdate(panel.id, panel, updates),
        onDelete: () => onPanelDelete(panel.id),
        onOpenCharacterPicker: () => onOpenCharacterPicker(panel.id),
        onOpenLocationPicker: () => onOpenLocationPicker(panel.id),
        onRetrySave: () => onRetryPanelSave(panel.id),
        onRemoveCharacter: (characterIndex) =>
          onRemoveCharacter(panel, characterIndex),
        onRemoveLocation: () => onRemoveLocation(panel),
        onRegeneratePanelImage,
        onOpenEditModal: () => onOpenEditModal(index),
        onOpenAIDataModal: () => onOpenAIDataModal(index),
        onSelectCandidateIndex: onSelectPanelCandidateIndex,
        onConfirmCandidate: onConfirmPanelCandidate,
        onCancelCandidate: onCancelPanelCandidate,
        onClearError: () => onClearPanelTaskError(panel.id),
        onPreviewImage,
        onInsertAfter: () => onInsertAfter(index),
        onVariant: () => onVariant(index),
        isInsertDisabled: isInsertDisabled(panel.id),
      }) satisfies ComponentProps<typeof PanelCard>,
    [
      globalPanelNumber,
      hasUnsavedChanges,
      imageUrl,
      index,
      isInsertDisabled,
      isPanelDeleting,
      isPanelModifying,
      isPanelSaving,
      item,
      panelCardLabels,
      onCancelPanelCandidate,
      onClearPanelTaskError,
      onConfirmPanelCandidate,
      onInsertAfter,
      onOpenAIDataModal,
      onOpenCharacterPicker,
      onOpenEditModal,
      onOpenLocationPicker,
      onPanelDelete,
      onPanelUpdate,
      onPreviewImage,
      onRegeneratePanelImage,
      onRemoveCharacter,
      onRemoveLocation,
      onRetryPanelSave,
      onSelectPanelCandidateIndex,
      onVariant,
      panel,
      panelCandidateData,
      panelData,
      panelFailedError,
      panelSaveError,
      panelTaskRunning,
      videoRatio,
      storyboardId,
    ],
  )
}
